name: CI/CD Pipeline for Accessory Streamlit App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  train-model:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create models directory if needed
      run: |
        mkdir -p models

    - name: Train and Save Models
      run: |
        python train_model.py

    - name: Push Trained Models to GitHub
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add models/model.keras models/model.tflite
        git commit -m "Update trained models via GitHub Actions"
        git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main

  deploy-streamlit:
    needs: train-model
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy to Streamlit Sharing
      run: echo "Deployment will happen automatically when you link the GitHub repo to Streamlit Cloud."
